#server:
#  port: 9000
# in order to push line

logging:
  level:
    org:
      springframework:
        security: INFO

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          client:
            registration:
              client-id: "client"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
#                - "http://127.0.0.1:8080/login/oauth2/code/spring"
                - "http://terrain.eastview.com/login/oauth2/code/spring"
              post-logout-redirect-uris:
#                - "http://127.0.0.1:8080/logged-out"
                - "http://terrain.eastview.com/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "user.read"
                - "user.write"
            require-authorization-consent: false
            require-proof-key: false

          client2:
            registration:
              client-id: "client2"
              client-secret: "{noop}secret2"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
#                - "http://127.0.0.1:8082/login/oauth2/code/spring"
                - "http://taou.eastview.com/login/oauth2/code/spring"
              post-logout-redirect-uris:
#                - "http://127.0.0.1:8082/logged-out"
                - "http://taou.eastview.com/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "user.read"
                - "user.write"
            require-authorization-consent: false
            require-proof-key: false

          client3:
            registration:
              client-id: "client3"
              client-secret: "{noop}secret3"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
#                - "http://127.0.0.1:8082/login/oauth2/code/spring"
                - "http://taus.eastview.com/login/oauth2/code/spring"
              post-logout-redirect-uris:
#                - "http://127.0.0.1:8082/logged-out"
                - "http://taus.eastview.com/logged-out"
              scopes:
                - "openid"
                - "profile"
                - "user.read"
                - "user.write"
            require-authorization-consent: false
            require-proof-key: false



    #datasource local

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/authorizationserverstorage}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
